<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <RootNamespace>LearnOpenTK.Lighting</RootNamespace>
    <AssemblyName>LearnOpenTK.Lighting</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Shaders\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.0" />
    <ProjectReference Include="..\..\Common\Common.csproj" />
  </ItemGroup>
</Project>
